### PR TITLE
feat: Add quotes of inspirational ,Programming, Life categories 

### PR DESCRIPTION
**Pull request by git-create-devben**
# PULL REQUEST TEMPLATE

**My PR closes #issue_number_here** 

### Note to reviewers

# 📷 Screenshots 

### ✔️ Check List (Check all the applicable boxes)

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
- [] I have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) properly and following the criteria.

### CODE REVIEW

**Comment by Shariar-Hasan** [comment]
read the contribution guideline

**Comment by git-create-devben** [comment]
> read the contribution guideline

Oh my bad I forgot to star the repo 🙈. please if there's anything please do let me know have already read the constitution guidelines. Thanks

**Comment by Shariar-Hasan** [comment]
No you didnt read the contribution guideline .
[reason ](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md#rules-for-adding-quotes:~:text=You%20must%20add%20minimum%20of%205%20Quotes%20to%20get%20your%20PR%20considered%20for%20merge)

**Review by git-create-devben — COMMENTED** [review]
Made some changes

**Comment by Shariar-Hasan** [comment]
all good,
just you have stared your forked repository.
not the original one 
image

**Comment by git-create-devben** [comment]
I just stared it now thanks 😊

**Comment by Shariar-Hasan** [comment]
All seems ok.
mearged

**Pull request merged**
