### PR TITLE
feat: Adding quotes of inspirational category For Life

### LINKED ISSUE #93: [OTHER] Add new Quotes
### Description

Try to add new quotes with previous categories.
you dont have to get assigned for adding quotes.
and make sure to [read the contribtion guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) 

### Screenshots

_No response_

### Additional information

_No response_

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
### Note to reviewers

# 📷 Screenshots 

Screenshot 2023-10-23 203842

### ✔ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR are clear and explain the approach.
- [x] I have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) properly and following the criteria.

### CODE REVIEW

**Comment by Shariar-Hasan** [comment]
can you star the repo, as it is the contribution criteria in guideline?

**Comment by Kapileswar-Moharana** [comment]
> can you star the repo, as it is the contribution criteria in guideline?

Done

**Comment by Kapileswar-Moharana** [comment]
@Shariar-Hasan Add Lebels to it Sir As Hacktoberfest Accepted

**Comment by Shariar-Hasan** [comment]
> @Shariar-Hasan Add Lebels to it Sir As Hacktoberfest Accepted, Otherwise it is not showing there in Webpage.

first check, its showing or not,
on my side, it should show,(maybe atleast after 15 minute)
as the condition was, either the repo must have hacktoberfest topic,
or PR must be merged as hacktoberfest-accepted.

can you check now?

**Comment by Kapileswar-Moharana** [comment]
> > @Shariar-Hasan Add Lebels to it Sir As Hacktoberfest Accepted, Otherwise it is not showing there in Webpage.
> 
> first check, its showing or not, on my side, it should show,(maybe atleast after 15 minute) as the condition was, either the repo must have hacktoberfest topic, or PR must be merged as hacktoberfest-accepted.
> 
> can you check now? it should show a **waiting** status

@Shariar-Hasan Not even showing the PR Itself waiting symbol is too far word sir , I think Sir You should have to assigned this Including PR and also have to add Hacktoberfest Accepted Lebel Then Only it Will Get Accepted,  Try Once if works 

Screenshot 2023-10-23 233440

**Comment by Shariar-Hasan** [comment]
Ok,
not a problem as i have already worked on so many repos, and most of them didnt accepted my PR without hacktoberfest tag,
dont know why its not showing in your showing in Your one.

**Comment by Kapileswar-Moharana** [comment]
@Shariar-Hasan Here Is One of My Accepted PR Look sir even he added Lebelss And assigned me in the PR page Also, Also it showing me as waiting then Got accepted

 
Screenshot 2023-10-23 234128

**Comment by Shariar-Hasan** [comment]
dont call me sir,
just call me by name 😀😀
ok,
no probelm best of luck

**Comment by Kapileswar-Moharana** [comment]
> don't call me sir, just call me by name 😀😀 ok, no probelm best of luck

@Shariar-Hasan OK Now it is showing as waiting, I think You should add labels in other PRs also maybe they are facing the same issue 

Screenshot 2023-10-23 234449

**Comment by Shariar-Hasan** [comment]
let me show you, then you will understand,
image
image
image

**Comment by Kapileswar-Moharana** [comment]
> let me show you, then you will understand, image image image

@Shariar-Hasan Hmm Ye bhhi to Haii Kuchh Hogaa sayad But after all Thanks

**Comment by Shariar-Hasan** [comment]
ok,
best of luck

**Pull request merged**
