### PR TITLE
feat: adding quotes of Educational  category

### PR DESCRIPTION
**Pull request by kratin01**
educational
category

#What This PR Do

**My PR  Added quotes** 

### 👨‍💻 What did you do ?

I have come across some truly inspiring quotes in the educational category. After scouring various platforms, I have handpicked the top 5 that I believe will leave a lasting impact on you. I hope you find them as thought-provoking and insightful as I did.

### Note to reviewers

# 📷 Screenshots 

quotes

### ✔️ Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) properly and following the criteria.

### CODE REVIEW

**Comment by Shariar-Hasan** [comment]
all good, but didnt read the contribution guideline

**Comment by kratin01** [comment]
I read the contribution guideline maybe I missed something I am so sorry about that  can you please let me know what's wrong or What I missed

**Comment by Shariar-Hasan** [comment]
now its okay,
you starred the repository.
all seems ok,
mearging 🆗✅

**Comment by kratin01** [comment]
sorry I just Missed That Part And Thanks For Merging...!!😊

**Pull request merged**
