### PR TITLE
feat: contribution Himanshi Rana

### PR DESCRIPTION
**Pull request by himanshirana2403**
# PULL REQUEST TEMPLATE

### ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) properly and following the criteria.

### CODE REVIEW

**Comment by Shariar-Hasan** [comment]
you are not following the contribution criteria of this repository.

**Comment by Shariar-Hasan** [comment]
if you are not interested in rules,
you can close this PR

**Comment by himanshirana2403** [comment]
> if you are not interested in rules, you can close this PR

sir can you please confirm which rule i haven't followed?

**Comment by Shariar-Hasan** [comment]
image
image

**Comment by himanshirana2403** [comment]
> image image

 sir i have star your reposita

> image image

done:)

**Comment by Shariar-Hasan** [comment]
be professional.
this might look little mistakes.
but rules are rules.

**Pull request merged**
