### PR TITLE
[FEATURE]:Added Whatsapp share button

### PR DESCRIPTION
**Pull request by rohits-web03**
#### It will easier to make the pull request for issue #12 after this pr is merged to maintain uniformity.

### CODE REVIEW

**Comment by Shariar-Hasan** [comment]
button is working fine,
UI is okay,
but a request, can you make a fetch from the repo,
as original repository is a bit ahead of yours,
for example.
image
this buttons are changed in original repo

**Comment by Shariar-Hasan** [comment]
> button is working fine, UI is okay, but a request, can you make a fetch from the repo, as original repository is a bit ahead of yours, for example. image this buttons are changed in original repo

can you work on this a bit?

**Comment by rohits-web03** [comment]
#### Did the whole ui change during this time?

**Comment by rohits-web03** [comment]
> #### Did the whole ui change during this time?

#### It now has a white background

**Comment by rohits-web03** [comment]
#### Hopefully it should be fine now

**Comment by Shariar-Hasan** [comment]
Excellent job 🔥

**Pull request merged**
