### PR TITLE
add new motivational quotes

### PR DESCRIPTION
**Pull request by ArpanMondalGITHUB**
# PULL REQUEST TEMPLATE

**My PR closes #issue_number_here** 

### Note to reviewers

# 📷 Screenshots 

### ✔️ Check List (Check all the applicable boxes)

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
- [] I have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) properly and following the criteria.

### CODE REVIEW

**Comment by Shariar-Hasan** [comment]
first read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md), then make PR,

**Comment by Shariar-Hasan** [comment]
if you are not interested in rules,
you can close this PR

**Comment by ArpanMondalGITHUB** [comment]
So sorry give me some time i will solve it

**Comment by ArpanMondalGITHUB** [comment]
@Shariar-Hasan should i make a other pr for contribution

**Comment by Shariar-Hasan** [comment]
yeah for sure,

**Pull request closed without merging**
