### PR TITLE
feat: adding quotes of mixed categories

### PR DESCRIPTION
**Pull request by therahulchaurasia**
Added 10 Quotes in Quotes.js under multiple categories.

### CODE REVIEW

**Comment by therahulchaurasia** [comment]
please merge my pr under hactoberfest2023

**Comment by Shariar-Hasan** [comment]
please star the repo and help us to grow

**Comment by therahulchaurasia** [comment]
Thanks a lot for merging my pull request and I have starred the repo

**Comment by Shariar-Hasan** [comment]
thanks for the support

**Pull request merged**
