### PR TITLE
Redesigned the share buttons

### LINKED ISSUE #118: [OTHER] Enhance Share with button
### Description

The "share with" option doesn't look very good. I would love to improve it's styling.

### Screenshots

image

### Additional information

_No response_

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by IbraheemHaseeb7**
# Redesigned the share buttons

**My PR closes #118  ** 

### 👨‍💻 What did you do ?

I redesigned the share buttons...added smooth animations on hover and overall aligned all the buttons perfectly. I also changed the whatsapp icon from the squared version to this normal version.

### Note to reviewers

# 📷 Screenshots 

bandicam 2023-10-23 16-03-03-258

### ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) properly and following the criteria.

### CODE REVIEW

**Comment by Shariar-Hasan** [comment]
your PR got cancelled due to not reading the contribtuion guideline

**Comment by IbraheemHaseeb7** [comment]
Hey I have reviewed the contributons.md, can you merge it now please?

**Comment by Shariar-Hasan** [comment]
did you read this?
image

**Comment by IbraheemHaseeb7** [comment]
I did read it but I have already submitted the PR quite a while ago. It was just a request on my end to merge it. Anyways, if you don't want to merge it no worries. 

Best of luck 🙌

**Comment by Shariar-Hasan** [comment]
> I did read it but I have already submitted the PR quite a while ago. It was just a request on my end to merge it. Anyways, if you don't want to merge it no worries.
> 
> Best of luck 🙌

dont mind,
but rules are rules.
you just can not take anyone else issue, and make a PR,
be professional.
best of luck to you too.

**Pull request closed without merging**
