### PR TITLE
added 5 New Quotes

### PR DESCRIPTION
**Pull request by SyedSumaimaly**
feat: adding quotes of Programmers category

### CODE REVIEW

**Comment by Shariar-Hasan** [comment]
please follow the contribution guideline first.
you didnt  give star ⭐ the repositoy

**Comment by SyedSumaimaly** [comment]
Done..

**Comment by Shariar-Hasan** [comment]
> please follow the contribution guideline first. you didnt give star ⭐ the repositoy

.

**Comment by SyedSumaimaly** [comment]
image
Already Done Bro..

**Comment by Shariar-Hasan** [comment]
> image Already Done Bro..

ok now its done

**Review by Shariar-Hasan — APPROVED** [review]
all seems good 🆗
merging ✅

**Pull request merged**
