### PR TITLE
feat: Added 5 new quotes

### PR DESCRIPTION
**Pull request by dk172923**
# PULL REQUEST TEMPLATE

**My PR closes #77** 

### Note to reviewers

# 📷 Screenshots 

### ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I have read the [contribution guideline](https://github.com/Shariar-Hasan/QuoteVerse/blob/main/Contributing.md) properly and following the criteria.

### CODE REVIEW

**Comment by dk172923** [comment]
I have added 5 new quotes into quotes.js file

**Review by Shariar-Hasan — APPROVED** [review]
you didnt read the contribution guideline.
else overal sems ok,
star the repo to get merged

**Comment by dk172923** [comment]
> you didnt read the contribution guideline. else overal sems ok, star the repo to get merged

I have starred the repo.

**Comment by Shariar-Hasan** [comment]
Your pull request has been closed.
reason : spam + false trying
image

**Comment by Shariar-Hasan** [comment]
my mistake.
pull request merged.

**Pull request merged**
